#!/bin/sh
# A convenient script to use as exec.{start,stop} commands when
# creating a new jail that uses runit to start and supervise services.
export RUNLEVEL=$2
case "$1" in
start)
	# shellcheck source=runit/1
	. /usr/local/etc/runit/1
	# shellcheck source=runit/2
	. /usr/local/etc/runit/2
	;;
stop)
	# shellcheck source=runit/3
	. /usr/local/etc/runit/3
	;;
esac
