#!/bin/sh
[ -r conf ] && . ./conf
# Perform weekly maintenance.
exec snooze -M 15 -H 4 -w 6 \
	env \
	HOME=/root \
	PATH=/etc:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/sbin \
	/usr/sbin/periodic weekly 2>&1
