#!/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /usr/local/etc/runit/functions

msg "Welcome to FreeBSD!"

if kenv -q boot_single > /dev/null; then
	if [ "x$(kenv boot_single)" = "xYES" ]; then
		emergency_shell
	fi
fi

# Start core services: one-time system tasks.
detect_virt
for f in /usr/local/etc/runit/core-services/*.sh; do
	[ -r $f ] && . $f
done

( umask 022 ; /sbin/dmesg > /var/run/dmesg.boot )

mkdir -p /var/run/runit
rm -rf /var/run/runit/*
install -m100 /dev/null /var/run/runit/stopit

msg "Initialization complete, running stage 2..."
