#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

runlevel=default
if kenv -q runlevel > /dev/null; then
	arg=$(/bin/kenv runlevel)
	if [ -d /usr/local/etc/runit/runsvdir/"$arg" ]; then
		echo "Runlevel detected: '$arg' (via kernel environment)"
		runlevel="$arg"
	fi
fi

[ -x /etc/rc.local ] && /etc/rc.local

runsvchdir "${runlevel}"
mkdir -p /var/run/runit/runsvdir
ln -sf /usr/local/etc/runit/runsvdir/current /var/run/runit/runsvdir/current

exec env - PATH=$PATH runsvdir -P /var/run/runit/runsvdir/current 'log: ...........................................................................................................................................................................................................................................................................................................................................................................................................'
