#!/bin/sh
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

runlevel=default
if kenv -q runit.runlevel > /dev/null; then
	arg=$(kenv runit.runlevel)
	if [ -d /usr/local/etc/runit/runsvdir/"$arg" ]; then
		echo "Runlevel detected via kenv: '$arg'"
		runlevel="$arg"
	fi
elif [ -n "${RUNLEVEL}" ]; then
	if [ -d /usr/local/etc/runit/runsvdir/"${RUNLEVEL}" ]; then
		echo "Runlevel detected via environment: '${RUNLEVEL}'"
		runlevel="${RUNLEVEL}"
	fi
fi

[ -x /etc/rc.local ] && /etc/rc.local

runsvchdir "${runlevel}" || emergency_shell
rm -rf /var/run/runit/runsvdir
mkdir -p /var/run/runit/runsvdir
ln -s /usr/local/etc/runit/runsvdir/current /var/run/runit/runsvdir/current

exec env - PATH=$PATH runsvdir -P /var/run/runit/runsvdir/current 'log: ...........................................................................................................................................................................................................................................................................................................................................................................................................'
