#!/bin/sh
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

. /usr/local/etc/runit/functions
detect_virt
[ -r /etc/rc.conf ] && . /etc/rc.conf

if [ -e /var/run/runit/reboot ]; then
	chmod 100 /var/run/runit/reboot
fi

echo
msg "Waiting for services to stop..."
sv force-stop /var/service/*
sv exit /var/service/*

[ -r /etc/rc.shutdown ] && . /etc/rc.shutdown
