#!/bin/sh

PATH=/usr/bin:/usr/sbin:/rescue
MSG="System is going down..."

# We check for this file in stage3 to halt or reboot
touch /var/run/runit/reboot

# Proceed with shutdown process
echo "$MSG" | wall
