#!/bin/sh
[ -r conf ] && . ./conf
: "${OPTS:="-s"}"
# if dbus is enabled wait for it.
if [ -e /var/service/dbus ]; then
	sv check dbus >/dev/null || exit 1
fi
# shellcheck disable=SC2086
exec avahi-daemon ${OPTS} 2>&1
