#!/bin/sh
set -eu
[ -r conf ] && . ./conf
: "${BHYVE:=/usr/sbin/bhyve}"
: "${BOOTROM:=/usr/local/share/uefi-firmware/BHYVE_UEFI.fd}"
: "${OPTS:=}"

# bhyve@<name>@<mem>@<cpus>@<bridge>
myifs="${IFS}"
IFS="@"
i=0
for f in ${PWD}; do
	case ${i} in
	1) name=${f} ;;
	2) mem=${f} ;;
	3) cpus=${f} ;;
	4) bridge=${f} ;;
	5) exit 1 ;;
	esac
	i=$((i + 1))
done
IFS="${myifs}"

: "${mem:=512m}"
: "${cpus:=1}"
: "${bridge:=bhyve0}"

if ! ifconfig ${bridge} >/dev/null 2>&1; then
	ifconfig bridge create name ${bridge} group runit-managed up
fi
kldload -qn nmdm
kldload -qn if_tap
sysctl net.link.tap.up_on_open=1 >/dev/null

slots="-s 0,hostbridge"
[ -r "cdrom" ] && slots="${slots} -s 1,ahci-cd,$(readlink cdrom)"
for i in $(seq 0 15); do
	if [ -r "disk${i}" ]; then
		disk="$(readlink "disk${i}")"
		slots="${slots} -s $((i + 2)),virtio-blk,${disk},nocache,direct"
	fi
done

intf=$(ifconfig tap create group "bhyve-${name}" group runit-managed)
ifconfig "${bridge}" addm "${intf}"
slots="${slots} -s 18,virtio-net,${intf}"
slots="${slots}	-s 31,lpc"

# shellcheck disable=SC2086
exec ${BHYVE} -A -H -P \
	-c ${cpus} \
	-m ${mem} \
	${slots} \
	-l "com1,/dev/nmdm${name}A" \
	-l "bootrom,${BOOTROM}" \
	${OPTS} \
	"${name}"
