#!/bin/sh
[ -r conf ] && . ./conf
: ${SNOOZE_ARGS="-H'*' -M'/5'"}
# gitqueue@$path@$branch[@$user] e.g. gitqueue@__usr__src@master
repo_path=$(echo "${PWD}" | awk -F@ '{ gsub("__", "/", $2); print $2 }')
branch=$(echo "${PWD}" | awk -F@ '{ print $3 }')
chuser=$(echo "${PWD}" | awk -F@ '{ if ($4 != "") { printf "chpst -u %s\n", $4 } }')
exec ${chuser} /usr/local/bin/snooze ${SNOOZE_ARGS} "${PWD}/update" 2>&1
