#!/bin/sh
[ -r ./conf ] && . ./conf
: ${CONF_FILE:=/etc/wpa_supplicant.conf}
: ${WPA_INTERFACE:=wlan0}
: ${WPA_SUPPLICANT:=/usr/sbin/wpa_supplicant}

# Wait for interface
while ! ifconfig ${WPA_INTERFACE} > /dev/null 2>&1; do
	sleep 1
done
exec 2>&1
exec ${WPA_SUPPLICANT} -Dbsd -c ${CONF_FILE} -i ${WPA_INTERFACE:=wlan0} -s ${OPTS}
